---
- hosts: aws #change to your hosts

  vars:

  tasks:
    - name: Wait for cloud-init / user-data to finish
      command: cloud-init status --wait
      changed_when: false

    - name: Delete scoring engine directory start clean
      ansible.builtin.file:
        path: /home/ubuntu/pysel
        state: absent

    
    - name: clone scoring engine forked repo from github
      command: chdir=/home/ubuntu/ git clone https://github.com/flyingdrnick/pysel
    
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/ubuntu/Desktop
        state: directory
        mode: '0755'

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/ubuntu/Documents
        state: directory
        mode: '0755'

    - name: Creating an passwords.csv empty file
      ansible.builtin.file:
        path: "/home/ubuntu/Documents/passwords.csv"
        state: touch
        mode: u=rw,g=r,o=r

    - name: copy forensic question 1
      copy:
        src: /home/ubuntu/pysel/static/ForensicQuestion1.txt
        remote_src: true
        dest: /home/ubuntu/Desktop/ForensicQuestion1.txt

    - name: copy forensic question 2
      copy:
        src: /home/ubuntu/pysel/static/ForensicQuestion2.txt
        remote_src: true
        dest: /home/ubuntu/Desktop/ForensicQuestion2.txt

    - name: copy competition README.txt 
      copy:
        src: /home/ubuntu/pysel/static/Readme.txt
        remote_src: true
        dest: /home/ubuntu/Desktop/Readme.txt

    - name: make script executable
      ansible.builtin.file:
        path: /home/ubuntu/pysel/quickinstall.sh
        state: touch
        mode: u=rx,g=rx,o=rx

    - name: install scoring engine
      command: chdir=/home/ubuntu/pysel sudo ./quickinstall.sh
      become: