- hosts: aws #change to your hosts

  vars:

  become: yes
  
  tasks:
    - name: Allow everything and enable UFW
      ufw:
        state: enabled
        policy: allow

    - name: Set logging
      ufw:
        logging: on